"""Compose ready-to-paste system prompts (profiles/) from behavioral modules (modules/).

Usage: python build.py
"""

from pathlib import Path

ROOT = Path(__file__).parent
MODULES = ROOT / "modules"
PROFILES = ROOT / "profiles"

PROFILE_SPECS = {
    "assistant": {
        "title": "Assistant Profile",
        "preamble": (
            "You are an assistant working with a user in conversation. The rules below "
            "govern how you communicate, when you act versus ask, and how faithfully you "
            "report what you did. They are binding, not advisory."
        ),
        "modules": ["communication", "autonomy", "integrity"],
    },
    "coding-agent": {
        "title": "Coding Agent Profile",
        "preamble": (
            "You are a coding agent working in a real codebase with real tools. The user may "
            "not be watching in real time and reads only what you write. The rules below "
            "govern communication, autonomy, honesty, safety around irreversible actions, "
            "and how you write code. They are binding, not advisory."
        ),
        "modules": ["communication", "autonomy", "integrity", "caution", "code"],
    },
    "autonomous-agent": {
        "title": "Autonomous Agent Profile",
        "preamble": (
            "You are an autonomous agent running with minimal supervision. No one can answer "
            "questions mid-task, and no one sees your intermediate steps — only your final "
            "report and your side effects. The rules below are your operating constraints. "
            "They are binding, not advisory."
        ),
        "modules": ["communication", "autonomy", "integrity", "caution"],
    },
}

GENERATED_NOTE = "<!-- Generated by build.py — edit modules/*.md, not this file. -->"


def module_body(name: str) -> str:
    text = (MODULES / f"{name}.md").read_text(encoding="utf-8").strip()
    lines = text.splitlines()
    # drop the H1; keep the scope line and rules
    if lines and lines[0].startswith("# "):
        heading = lines[0][2:].strip()
        lines = [f"## {heading}"] + lines[1:]
    return "\n".join(lines).replace("\n## ", "\n### ").replace("\n### Module:", "\n## Module:")


def build() -> None:
    PROFILES.mkdir(exist_ok=True)
    for slug, spec in PROFILE_SPECS.items():
        parts = [GENERATED_NOTE, f"# {spec['title']}", "", spec["preamble"], ""]
        parts += [module_body(m) + "\n" for m in spec["modules"]]
        out = PROFILES / f"{slug}.md"
        out.write_text("\n".join(parts), encoding="utf-8", newline="\n")
        print(f"built profiles/{slug}.md ({len(spec['modules'])} modules)")


if __name__ == "__main__":
    build()
